#!/bin/sh

case "${UACTIVITY_ORGIN}" in
  startup)
    logger -t "uactivity [watchdog/$(basename ${0})]" "watchdog starting up"
    [ "${UACTIVITY_INFO_ACTIVITY}" = "true" ] \
      && logger -t "uactivity [watchdog/$(basename ${0})]" "status \"user active\"" \
      || logger -t "uactivity [watchdog/$(basename ${0})]" "status \"user inactive\"" 
    logger -t "uactivity [watchdog/$(basename ${0})]" "ConfigDirectory:   ${UACTIVITY_CONFIGDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "CacheDirectory:    ${UACTIVITY_CACHEDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ResourceDirectory: ${UACTIVITY_RESOURCEDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "Key:               ${UACTIVITY_INFO_KEY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "VideoDirectory:    ${UACTIVITY_INFO_VIDEODIR}"
  ;;
  started)
    logger -t "uactivity [watchdog/$(basename ${0})]" "watchdog started"
    [ "${UACTIVITY_INFO_ACTIVITY}" = "true" ] \
      && logger -t "uactivity [watchdog/$(basename ${0})]" "status \"user active\"" \
      || logger -t "uactivity [watchdog/$(basename ${0})]" "status \"user inactive\"" 
    logger -t "uactivity [watchdog/$(basename ${0})]" "ConfigDirectory:   ${UACTIVITY_CONFIGDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "CacheDirectory:    ${UACTIVITY_CACHEDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ResourceDirectory: ${UACTIVITY_RESOURCEDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "Key:               ${UACTIVITY_INFO_KEY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "VideoDirectory:    ${UACTIVITY_INFO_VIDEODIR}"
  ;;
  shutdown)
    logger -t "uactivity [watchdog/$(basename ${0})]" "watchdog shutting down"
    [ "${UACTIVITY_INFO_ACTIVITY}" = "true" ] \
      && logger -t "uactivity [watchdog/$(basename ${0})]" "status \"user active\"" \
      || logger -t "uactivity [watchdog/$(basename ${0})]" "status \"user inactive\"" 
    logger -t "uactivity [watchdog/$(basename ${0})]" "ConfigDirectory:   ${UACTIVITY_CONFIGDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "CacheDirectory:    ${UACTIVITY_CACHEDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ResourceDirectory: ${UACTIVITY_RESOURCEDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "Key:               ${UACTIVITY_INFO_KEY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "VideoDirectory:    ${UACTIVITY_INFO_VIDEODIR}"
  ;;
  running)
    logger -t "uactivity [watchdog/$(basename ${0})]" "watchdog triggered"
    [ "${UACTIVITY_INFO_ACTIVITY}" = "true" ] \
      && logger -t "uactivity [watchdog/$(basename ${0})]" "status \"user active\"" \
      || logger -t "uactivity [watchdog/$(basename ${0})]" "status \"user inactive\"" 
    logger -t "uactivity [watchdog/$(basename ${0})]" "ConfigDirectory:   ${UACTIVITY_CONFIGDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "CacheDirectory:    ${UACTIVITY_CACHEDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ResourceDirectory: ${UACTIVITY_RESOURCEDIRECTORY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "Key:               ${UACTIVITY_INFO_KEY}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "VideoDirectory:    ${UACTIVITY_INFO_VIDEODIR}"
  ;;
esac

exit 0
