#!/bin/sh

case "${1}" in
  startup)
    logger -t "uactivity [watchdog/$(basename ${0})]" "watchdog starting up"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ConfigDirectory:   ${3}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "CacheDirectory:    ${4}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ResourceDirectory: ${5}"
  ;;
  shutdown)
    logger -t "uactivity [watchdog/$(basename ${0})]" "watchdog shutting down"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ConfigDirectory:   ${3}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "CacheDirectory:    ${4}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ResourceDirectory: ${5}"
  ;;
  running)
    logger -t "uactivity [watchdog/$(basename ${0})]" "watchdog triggered"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ConfigDirectory:   ${3}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "CacheDirectory:    ${4}"
    logger -t "uactivity [watchdog/$(basename ${0})]" "ResourceDirectory: ${5}"
  ;;
esac

exit 0
