#!/bin/sh

case "${UACTIVITY_ORGIN}" in
  startup)
    logger -t "uactivity [key/$(basename ${0})]" "key starting up"
    logger -t "uactivity [key/$(basename ${0})]" "ConfigDirectory:   ${UACTIVITY_CONFIGDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "CacheDirectory:    ${UACTIVITY_CACHEDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "ResourceDirectory: ${UACTIVITY_RESOURCEDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "Key:               ${UACTIVITY_INFO_KEY}"
    logger -t "uactivity [key/$(basename ${0})]" "VideoDirectory:    ${UACTIVITY_INFO_VIDEODIR}"
  ;;
  started)
    logger -t "uactivity [key/$(basename ${0})]" "key started"
    logger -t "uactivity [key/$(basename ${0})]" "ConfigDirectory:   ${UACTIVITY_CONFIGDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "CacheDirectory:    ${UACTIVITY_CACHEDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "ResourceDirectory: ${UACTIVITY_RESOURCEDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "Key:               ${UACTIVITY_INFO_KEY}"
    logger -t "uactivity [key/$(basename ${0})]" "VideoDirectory:    ${UACTIVITY_INFO_VIDEODIR}"
  ;;
  shutdown)
    logger -t "uactivity [key/$(basename ${0})]" "key shutting down"
    logger -t "uactivity [key/$(basename ${0})]" "ConfigDirectory:   ${UACTIVITY_CONFIGDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "CacheDirectory:    ${UACTIVITY_CACHEDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "ResourceDirectory: ${UACTIVITY_RESOURCEDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "Key:               ${UACTIVITY_INFO_KEY}"
    logger -t "uactivity [key/$(basename ${0})]" "VideoDirectory:    ${UACTIVITY_INFO_VIDEODIR}"
  ;;
  running)
    logger -t "uactivity [key/$(basename ${0})]" "key \"${2}\" pressed"
    logger -t "uactivity [key/$(basename ${0})]" "ConfigDirectory:   ${UACTIVITY_CONFIGDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "CacheDirectory:    ${UACTIVITY_CACHEDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "ResourceDirectory: ${UACTIVITY_RESOURCEDIRECTORY}"
    logger -t "uactivity [key/$(basename ${0})]" "Key:               ${UACTIVITY_INFO_KEY}"
    logger -t "uactivity [key/$(basename ${0})]" "VideoDirectory:    ${UACTIVITY_INFO_VIDEODIR}"
  ;;
esac

exit 0
