#!/bin/sh

# we are interested in Key "1"
[ "${2}" != "1" ] && exit 0

case "${1}" in
  startup)
    # create flag directory (using cache directory)
    mkdir -p ${4}/key/
    # delete flag
    rm -f ${4}/key/$(basename ${0}).flag
  ;;
  running)
    if [ -f "${4}/key/flag.$(basename ${0})" ]; then
      # here we do our "off" action
      logger -t "uactivity [key/$(basename ${0})]" "$(basename ${0}) off"
      rm -f "${4}/key/flag.$(basename ${0})"
    else
      # here we do our "on" action
      logger -t "uactivity [key/$(basename ${0})]" "$(basename ${0}) on"
      # do not use names starting with [0-9][0-9] for data files
      touch "${4}/key/flag.$(basename ${0})"
    fi
  ;;
esac

exit 0
