#!/bin/sh

switch_tv(){
  if [ "${1}" = "on" ]; then
    # yaUSBir sometimes ignore the first command, send an existing dummy ir code
    irsend -d /var/run/lirc/ya_usbir SEND_ONCE TV_DUMMY dummy
    sleep 0.5
    irsend -d /var/run/lirc/ya_usbir SEND_ONCE TV_REMOTE on
  else
    # yaUSBir sometimes ignore the first command, send an existing dummy ir code
    irsend -d /var/run/lirc/ya_usbir SEND_ONCE TV_DUMMY dummy
    sleep 0.5
    irsend -d /var/run/lirc/ya_usbir SEND_ONCE TV_REMOTE off
  fi
}



case "${1}" in
  startup)
    true
  ;;
  started)
    [ "${2}" = "true" ] && switch_tv on
  ;;
  shutdown)
    switch_tv off
  ;;
  running)
    if [ "${2}" = "true" ]; then
      switch_tv on
    else
      switch_tv off
    fi
  ;;
esac

exit 0
