#!/bin/sh

case "${1}" in
  startup)
    logger -t "uactivity [activity/$(basename ${0})]" "activity starting up"
    [ "${2}" = "true" ] \
      && logger -t "uactivity [activity/$(basename ${0})]" "status \"user active\"" \
      || logger -t "uactivity [activity/$(basename ${0})]" "status \"user inactive\""
    logger -t "uactivity [activity/$(basename ${0})]" "ConfigDirectory:   ${3}"
    logger -t "uactivity [activity/$(basename ${0})]" "CacheDirectory:    ${4}"
    logger -t "uactivity [activity/$(basename ${0})]" "ResourceDirectory: ${5}"
  ;;
  started)
    logger -t "uactivity [activity/$(basename ${0})]" "activity started"
    [ "${2}" = "true" ] \
      && logger -t "uactivity [activity/$(basename ${0})]" "status \"user active\"" \
      || logger -t "uactivity [activity/$(basename ${0})]" "status \"user inactive\""
    logger -t "uactivity [activity/$(basename ${0})]" "ConfigDirectory:   ${3}"
    logger -t "uactivity [activity/$(basename ${0})]" "CacheDirectory:    ${4}"
    logger -t "uactivity [activity/$(basename ${0})]" "ResourceDirectory: ${5}"
  ;;
  shutdown)
    logger -t "uactivity [activity/$(basename ${0})]" "activity shutting down"
    [ "${2}" = "true" ] \
      && logger -t "uactivity [activity/$(basename ${0})]" "status \"user active\"" \
      || logger -t "uactivity [activity/$(basename ${0})]" "status \"user inactive\""
    logger -t "uactivity [activity/$(basename ${0})]" "ConfigDirectory:   ${3}"
    logger -t "uactivity [activity/$(basename ${0})]" "CacheDirectory:    ${4}"
    logger -t "uactivity [activity/$(basename ${0})]" "ResourceDirectory: ${5}"
  ;;
  running)
    logger -t "uactivity [activity/$(basename ${0})]" "activity status changed"
    [ "${2}" = "true" ] \
      && logger -t "uactivity [activity/$(basename ${0})]" "status \"user active\"" \
      || logger -t "uactivity [activity/$(basename ${0})]" "status \"user inactive\""
    logger -t "uactivity [activity/$(basename ${0})]" "ConfigDirectory:   ${3}"
    logger -t "uactivity [activity/$(basename ${0})]" "CacheDirectory:    ${4}"
    logger -t "uactivity [activity/$(basename ${0})]" "ResourceDirectory: ${5}"
  ;;
esac

exit 0
