#!/bin/sh

# Log to syslog and to stderr
LOG="mylog"

mylog() {
  [ -n "$(which logger)" ] && logger -t $(basename ${0}) "${1}"
  echo "${1}" >&2;
}

usage(){
	${LOG} "Usage: $(basename $0) -r <reason activity|key|watchdog> -o <orgin startup|started|shutdown|running>"
	${LOG} "                     -C <ConfigDirectory> -c <CacheDirectory> -R <ResourceDirectory>"
	${LOG} "                     -A <activity> -K <Key> -V <Video Directory>"
	${LOG} "$cmd_error"
	exit 1
}

cmd_error=""
while getopts "r:o:C:c:R:A:K:V:" opt; do
	case "$opt" in
		r) PARAM_REASON="$OPTARG";;
		o) PARAM_ORGIN="$OPTARG";;
		C) PARAM_CONFIGDIRECTORY="$OPTARG";;
		c) PARAM_CACHEDIRECTORY="$OPTARG";;
		R) PARAM_RESOURCEDIRECTORY="$OPTARG";;
		A) PARAM_ACTIVITY="$OPTARG";;
		K) PARAM_KEY="$OPTARG";;
		V) PARAM_VIDEODIR="$OPTARG";;
		--) break;;
		\?) cmd_error="Error: Error parsing Commandline"; break;;
	esac
done

[ -n "$cmd_error" ] && usage

# we could ovveride the directories for FHS
[ -r "${PARAM_CONFIGDIRECTORY}/directories.conf" ] && . "${PARAM_CONFIGDIRECTORY}/directories.conf"

# Exit if nothing to do
[ -d "${PARAM_CONFIGDIRECTORY}/${PARAM_REASON}" ] || exit 0

# Export the Values for the activity scripts
UACTIVITY_ORGIN="${PARAM_ORGIN}"
export UACTIVITY_ORGIN

UACTIVITY_CONFIGDIRECTORY="${PARAM_CONFIGDIRECTORY}"
UACTIVITY_CACHEDIRECTORY="${PARAM_CACHEDIRECTORY}"
UACTIVITY_RESOURCEDIRECTORY="${PARAM_RESOURCEDIRECTORY}"
export UACTIVITY_CONFIGDIRECTORY UACTIVITY_CACHEDIRECTORY UACTIVITY_RESOURCEDIRECTORY

UACTIVITY_INFO_ACTIVITY="${PARAM_ACTIVITY}"
UACTIVITY_INFO_KEY="${PARAM_KEY}"
UACTIVITY_INFO_VIDEODIR="${PARAM_VIDEODIR}"
export UACTIVITY_INFO_ACTIVITY UACTIVITY_INFO_KEY UACTIVITY_INFO_VIDEODIR

hooks="$(find "${PARAM_CONFIGDIRECTORY}/${PARAM_REASON}" -maxdepth 1 -xtype f -name '[0-9][0-9]*' | sort)" 
for hook in ${hooks}; do
    if [ -x "${hook}" ]; then
        eval "${hook}"
    else
        eval /bin/sh "${hook}"
    fi
    [ $? -ne 0 ] && ${LOG} "error when executing ${hook}"
done

exit 0
